void Server_Admin_Login(int);
void Server_Create_FlatAccount(int);
void Server_Delete_Account(int);
void Server_View_ApplianceStatus(int);
void Server_Generate_Report(int);
void Server_FlatOwner_Login(int);
void Server_Register_Appliance(int);
void Server_Modify_ApplianceControl(int);
void Server_Add_FamilyMembers(int);
void Server_Change_LoginCredentials(int);
void Create_Tables(void);
//void Mysql_Error(MYSQL *);
void server_menu(int);
void Server_Admin_Menu(int);
void Server_FamilyMember_Login(int);
void Server_FamilyMember_Menu(int);
void Server_FlatOwner_Menu(int);
void Server_Modify_Registration(int);
void Server_UnRegister(int);
void Server_Sighandler(int);
void Send_message(int ,char []);
char* Receive_Message(int);
void Server_Modify_ApplianceControl(int);
void Server_Control_Appliance(int);
